---
cloud_service_group: SecretsManager
cloud_service_type: Secret
name: Secret per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
