---
cloud_service_group: ECS
cloud_service_type: Cluster
name: Active Service Total Count
query:
  aggregate:
    - unwind:
        path: data.services
    - group:
        fields:
        - name: value
          key: data.services
          operator: count
