---
cloud_service_group: EC2
cloud_service_type: AutoScalingGroup
name: Count by Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            operator: count
options:
  chart_type: COLUMN
