---
cloud_service_group: EC2
cloud_service_type: AutoScalingGroup
name: Auto Scaling Group per Region
query:
  aggregate:
    - unwind:
        path: data.instances
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            key: data.instances
            operator: count
options:
  chart_type: COLUMN
