---
cloud_service_group: ELB
cloud_service_type: LoadBalancer
name: Load Balancer per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
