---
cloud_service_group: SQS
cloud_service_type: Queue
name: Queue count per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
