---
cloud_service_group: EC2
cloud_service_type: Volume
name: Volume Total Size per Volume Type
query:
  aggregate:
    - group:
        keys:
          - name: volume_type
            key: instance_type
        fields:
          - name: size
            key: instance_size
            operator: sum
options:
  chart_type: TREEMAP