---
cloud_service_group: EC2
cloud_service_type: Volume
name: Total Size by Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            key: instance_size
            operator: sum
options:
  chart_type: COLUMN
  name_options:
    key: name
    reference:
      resource_type: "inventory.Region"
      reference_key: region_code
  value_options:
    key: value
    type: size
