---
cloud_service_group: KinesisFirehose
cloud_service_type: DeliveryStream
name: Delivery Stream per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
