---
cloud_service_group: Lambda
cloud_service_type: Function
name: Function per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
