---
cloud_service_group: EFS
cloud_service_type: FileSystem
name: File System Count per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
