---
cloud_service_group: EFS
cloud_service_type: FileSystem
name: Mount Target Count by Availability Zone
query:
  aggregate:
    - unwind:
        path: data.mount_targets
    - group:
        keys:
          - name: name
            key: data.mount_targets.availability_zone_name
        fields:
          - name: value
            key: data.mount_targets
            operator: count
options:
  chart_type: COLUMN
