---
cloud_service_group: DynamoDB
cloud_service_type: Table
name: Item Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            operator: sum
            key: data.item_count
