---
cloud_service_group: DynamoDB
cloud_service_type: Table
name: Snapshot Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            operator: sum
            key: instance_size
