---
cloud_service_group: DynamoDB
cloud_service_type: Table
name: Top 5 Table Size
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: name
          - name: value
            key: instance_size
    - sort:
        key: value
        desc: true
options:
  chart_type: COLUMN
