---
cloud_service_group: DynamoDB
cloud_service_type: Table
name: Write Capacity Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            operator: sum
            key: data.total_write_capacity
