---
cloud_service_group: VPC
cloud_service_type: InternetGateway
name: Internet Gateway count per Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            operator: count
options:
  chart_type: COLUMN
