---
cloud_service_group: VPC
cloud_service_type: VPNConnection
name: VPN Connection count per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
