---
cloud_service_group: DocumentDB
cloud_service_type: Cluster
name: Instance per Availability Zone
query:
  aggregate:
    - unwind:
        path: data.instances
    - group:
        keys:
          - name: name
            key: data.instances.availability_zone
        fields:
          - name: value
            key: data.instances.availability_zone
            operator: count
options:
  chart_type: COLUMN
