---
cloud_service_group: DocumentDB
cloud_service_type: Cluster
name: Snapshot Total Count
query:
  aggregate:
    - unwind:
        path: data.snapshots
    - group:
        fields:
          - name: value
            operator: count
            key: data.snapshots
