---
cloud_service_group: DirectConnect
cloud_service_type: LAG
name: LAG per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
