######
# bandwidth 단위와 type 변경 작업 먼저 해야함..
######
---
cloud_service_group: DirectConnect
cloud_service_type: LAG
name: LAG Bandwidth Total Sum
query:
  aggregate:
    - unwind:
        path: data.connections
    - group:
        fields:
          - name: value
            operator: sum
            key: data.connections.bandwidth_gbps
