---
cloud_service_group: DirectConnect
cloud_service_type: VirtualPrivateGateway
name: Virtual Private Gateway per Account
query:
  aggregate:
    - group:
        keys:
          - name: account
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
