---
cloud_service_group: Redshift
cloud_service_type: Cluster
name: Cluster per Account
query:
  aggregate:
    - group:
        keys:
          - name: account
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
