---
cloud_service_group: IAM
cloud_service_type: User
name: MFA Not used user Total Count
query:
  aggregate:
  - group:
      fields:
      - name: value
        operator: count
        conditions:
        - key: data.sign_in_credential.console_password
          value: Enabled
          operator: eq
        - key: data.mfa_device
          value: Not enabled
          operator: eq