---
cloud_service_group: RDS
cloud_service_type: Database
name: Database per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
