---
cloud_service_group: S3
cloud_service_type: Bucket
name: Bucket Count by Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT