---
cloud_service_group: S3
cloud_service_type: Bucket
name: Object count per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: data.object_count
            operator: sum
options:
  chart_type: DONUT