---
cloud_service_group: S3
cloud_service_type: Bucket
name: Object Total Size per Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            key: instance_size
            operator: sum
options:
  chart_type: COLUMN
  value_options:
    key: value
    type: size