---
cloud_service_group: KinesisDataStream
cloud_service_type: DataStream
name: Data Stream per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
