---
cloud_service_group: Route53
cloud_service_type: HostedZone
name: Record Set per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: data.resource_record_set_count
            operator: sum
options:
  chart_type: DONUT
