---
cloud_service_group: KMS
cloud_service_type: Key
name: Key per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
