---
cloud_service_group: CloudFront
cloud_service_type: Distribution
name: Distribution Count per Status
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.status
        fields:
          - name: value
            operator: count
options:
  chart_type: COLUMN
