---
cloud_service_group: CloudFront
cloud_service_type: Distribution
name: Distribution Count per Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.origins.items
        fields:
          - name: value
            operator: count
options:
  chart_type: COLUMN
